const CATALOG = [
    {
        id: 'el1',
        name: 'VOLKSWAGEN TOP',
        img: 'img/Volks.jpg',
        price: 3600,
    },
    {
        id: 'el2',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el3',
        name: 'GUAP',
        img: 'img/guap.png',
        price: 5500,
    },
    {
        id: 'el4',
        name: 'GUAP',
        img: 'img/guap.png',
        price: 5500,
    },
    {
        id: 'el5',
        name: 'GUAP',
        img: 'img/guap.png',
        price: 5500,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    {
        id: 'el6',
        name: 'FFIZRA',
        img: 'img/Vin.jpg',
        price: 3900,
    },
    
];
